language: r
sudo: false
cache: packages
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
r_github_packages:
- leeper/prediction
- leeper/margins
r_packages:
- knitr
- covr
after_success:
- if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
